name: Deploy and Track

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: appanil234
          package: .

      - name: Create Azure DevOps Work Item
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $(echo -n ":${{ secrets.AZURE_DEVOPS_PAT }}" | base64)" \
            -d '[
              {
                "op": "add",
                "path": "/fields/System.Title",
                "value": "Deployment triggered by GitHub Actions"
              },
              {
                "op": "add",
                "path": "/fields/System.Description",
                "value": "Deployed commit ${{ github.sha }} from repo ${{ github.repository }}"
              }
            ]' \
            https://dev.azure.com/${{ secrets.AZURE_DEVOPS_ORG }}/${{ secrets.AZURE_DEVOPS_PROJECT }}/_apis/wit/workitems/$Task?api-version=7.0
